/** Seed data — same rows as original HTML */
export const USERS = [
  {
    name: "Misxa Germino",
    email: "misxa@campus.edu",
    role: "organizer",
    roleLabel: "Student Organizer",
    status: "active",
    org: "DominiXode",
    course: "BSIT",
    rfid: "registered",
    lastActive: "1hr ago",
  },
  {
    name: "Amira Marqueses",
    email: "amira@campus.edu",
    role: "organizer",
    roleLabel: "Student Organizer",
    status: "active",
    org: "DominiXode",
    course: "BSIT",
    rfid: "registered",
    lastActive: "1hr ago",
  },
  {
    name: "Khrystelle Esplana",
    email: "khrystelle@campus.edu",
    role: "student",
    roleLabel: "Student",
    status: "active",
    org: "DominiXode",
    course: "BSIT",
    rfid: "registered",
    lastActive: "5hr ago",
  },
  {
    name: "Gwyneth Mucio",
    email: "gwyneth@campus.edu",
    role: "student",
    roleLabel: "Student",
    status: "active",
    org: "DominiXode",
    course: "BSIT",
    rfid: "registered",
    lastActive: "3hr ago",
  },
  {
    name: "Paul Cielo",
    email: "paul@campus.edu",
    role: "organizer",
    roleLabel: "Student Organizer",
    status: "active",
    org: "DominiXode",
    course: "BSIT",
    rfid: "registered",
    lastActive: "1 day ago",
  },
  {
    name: "Mae Mayuga",
    email: "mae@campus.edu",
    role: "student",
    roleLabel: "Student",
    status: "active",
    org: "DominiXode",
    course: "BSIT",
    rfid: "registered",
    lastActive: "1 day ago",
  },
  {
    name: "Ken Cabrales",
    email: "ken@campus.edu",
    role: "student",
    roleLabel: "Student",
    status: "inactive",
    org: "DominiXode",
    course: "BSIT",
    rfid: "not-registered",
    lastActive: "2 days ago",
  },
  {
    name: "Edel Naag",
    email: "edel@campus.edu",
    role: "student",
    roleLabel: "Student",
    status: "inactive",
    org: "DominiXode",
    course: "BSIT",
    rfid: "not-registered",
    lastActive: "3 days ago",
  },
  {
    name: "Daniel Nadal",
    email: "daniel@campus.edu",
    role: "student",
    roleLabel: "Student",
    status: "inactive",
    org: "DominiXode",
    course: "BSIT",
    rfid: "not-registered",
    lastActive: "4 days ago",
  },
  {
    name: "Beggy Balictar",
    email: "beggy@campus.edu",
    role: "student",
    roleLabel: "Student",
    status: "active",
    org: "DominiXode",
    course: "BSIT",
    rfid: "registered",
    lastActive: "4 days ago",
  },
];
